// Developer term -> UI label. The README glossary is the source of truth; keep them in sync.
export const labels = {
  planningPhase: 'Route Planner',
  itineraryDraft: 'Draft',
  lockedItinerary: 'The Route',
  approvalVote: 'Highball',
  like: 'Cheers',
  dislike: 'Pass',
  livePhase: 'Live',
  wrapUpPhase: 'Closing Time',
  admin: 'Conductor',
  users: 'Crew',
  userRoster: 'Crew Board',
  stop: 'Stop',
  dwell: 'Layover',
  trainLeg: 'Run',
  walk: 'Walk',
  venueCard: 'Stop card',
  departureBanner: 'Departure Board',
  firstWarning: 'Last Call',
  leaveNow: 'All Aboard',
  locationSharing: 'Position Report',
  checkIn: 'Punch',
  reroute: 'Reroute',
  hold: 'Hold',
  cancelStop: 'Annul',
  addStop: 'Extra',
  broadcast: 'Bulletin',
  eventLog: 'Train Sheet',
  drinkLog: 'Tab',
  scoreboard: 'Hall of Fame',
  awards: 'Golden Spikes',
  media: 'Freight',
  album: 'Roundhouse',
  simulationMode: 'Shakedown Run',
  simulationClock: 'Railroad Time',
  meetingPoint: 'Meet Point',
  straggler: 'Caboose',
  leftEarly: 'Deadhead',
  homeStation: 'Home Terminal'
} as const;

export type LabelKey = keyof typeof labels;

export function label(key: LabelKey): string {
  return labels[key];
}

// UI copy lives alongside the glossary so it can be changed in one place.
export const copy = {
  appTitle: 'Chug-a-Lug Choo-Choo',
  appSubtitle: 'Your next stop starts here.',
  loginTitle: 'Welcome aboard',
  loginIntro: 'Enter your name and the crew password from the family chat.',
  name: 'Your name',
  namePlaceholder: 'How the crew knows you',
  password: 'Crew password',
  login: 'Climb aboard',
  working: 'Please wait…',
  nameError: "Enter a name: 2 to 32 letters, numbers, spaces, or . ' -",
  passwordError: 'Enter the crew password.',
  genericError: 'Something went wrong. Please try again.',
  welcome: 'Welcome aboard,',
  role: 'You are part of the',
  comingSoon: 'Coming soon',
  homeIntro: 'You’re ready for the ride. Planning, live updates, and the album will arrive next.',
  notYou: 'Not you? Log out and enter your own name.',
  logout: 'Log out',
  footer: 'Family, friends, and the next train.',
  plannerTeaser: 'Propose stops, cheer the good ones, lock the winner.',
  plannerIntro: 'Anyone can start a draft and add stops. The Conductor runs the vote and locks The Route.',
  drafts: 'Drafts',
  pastRoutes: 'Locked and archived',
  newDraft: 'Start a draft',
  draftTitle: 'Draft title',
  draftTitlePlaceholder: 'e.g. West line classics',
  create: 'Create',
  noDrafts: 'No drafts yet. Start the first one.',
  status_draft: 'Draft',
  status_locked: 'Locked',
  status_archived: 'Archived',
  eventDate: 'Event day',
  startTime: 'At the first stop by',
  stops: 'Stops',
  addStop: 'Add a stop',
  noStops: 'No stops yet. Add the first bar.',
  arrive: 'Arrive',
  leave: 'Leave',
  layoverMinutes: 'min layover',
  walkMinutes: 'min walk to the station',
  moveUp: 'Move up',
  moveDown: 'Move down',
  remove: 'Remove',
  removeConfirm: 'Remove this stop?',
  computing: 'Working out the trains…',
  noTrain: 'No train works here. Shorten a layover, change the start time, or move this stop.',
  sameStation: 'Same station, walk over.',
  walk: 'Walk',
  minutes: 'min',
  departs: 'departs',
  arrives: 'arrives',
  changeAt: 'change at',
  deleteDraft: 'Delete draft',
  deleteDraftConfirm: 'Delete this draft and all its stops?',
  notAffiliated: 'Schedule from Metra’s public feed. Not affiliated with Metra. Saturday timetable, published',
  pickStation: 'Pick a station',
  pickStationHint: 'Tap a dot on the map or use the list.',
  stationList: 'All stations',
  nearby: 'Bars and restaurants within a 10-minute walk of',
  loadingNearby: 'Looking around the station…',
  noNearby: 'OpenStreetMap lists nothing here. Search by name instead.',
  searchByName: 'Search by name',
  searchPlaceholder: 'Bar or restaurant name',
  search: 'Search',
  searching: 'Searching…',
  noSearchResults: 'Nothing found. Add it by name only.',
  manualAdd: 'Add by name only',
  manualName: 'Name',
  add: 'Add',
  adding: 'Adding…',
  osmAttribution: 'Venue data © OpenStreetMap contributors',
  googleAttribution: 'Details and photos via Google',
  changeStation: 'Change station',
  kind_bar: 'Bar',
  kind_restaurant: 'Restaurant',
  kind_other: 'Place',
  openInMaps: 'Open in Google Maps',
  hours: 'Hours',
  hoursUnknown: 'Hours unknown. Call to confirm.',
  phone: 'Phone',
  website: 'Website',
  notes: 'Notes',
  notesPlaceholder: 'Deals, tips, who suggested it…',
  confirmedOpen: 'Confirmed open on event day',
  confirmPhone: 'Number called',
  photosPending: 'Fetching photos…',
  photosFailed: 'Photos unavailable.',
  retryPhotos: 'Try again',
  noPhotos: 'No photos yet.',
  save: 'Save',
  saved: 'Saved.',
  comments: 'Comments',
  commentPlaceholder: 'Say something…',
  post: 'Post',
  noComments: 'No comments yet.',
  delete: 'Delete',
  approvalIntro: 'The Conductor opens the vote. When the crew says go, the Conductor locks the route.',
  openVote: 'Open the vote',
  closeVote: 'Close the vote',
  voteOpen: 'The vote is open.',
  voteClosed: 'The vote is not open.',
  go: 'Go',
  nogo: 'No go',
  tally: 'Tally',
  lockRoute: 'Lock as The Route',
  lockConfirm: 'Lock this draft as The Route? Any other locked route is archived.',
  noRoute: 'No route is locked yet.',
  lockedOn: 'Locked on',
  backToPlanner: 'Back to the Route Planner',
  backToDraft: 'Back to the draft',
  loadError: 'Could not load this. Check your connection and try again.',
  stationOTC: 'Ogilvie',
  stationCUS: 'Union Station',
} as const;
