// Developer term -> UI label. The README glossary is the source of truth; keep them in sync.
export const labels = {
  planningPhase: 'Route Planner',
  itineraryDraft: 'Draft',
  lockedItinerary: 'The Route',
  approvalVote: 'Highball',
  like: 'Cheers',
  dislike: 'Pass',
  livePhase: 'Live',
  wrapUpPhase: 'Closing Time',
  admin: 'Conductor',
  users: 'Crew',
  userRoster: 'Crew Board',
  stop: 'Stop',
  dwell: 'Layover',
  trainLeg: 'Run',
  walk: 'Walk',
  venueCard: 'Stop card',
  departureBanner: 'Departure Board',
  firstWarning: 'Last Call',
  leaveNow: 'All Aboard',
  locationSharing: 'Position Report',
  checkIn: 'Punch',
  reroute: 'Reroute',
  hold: 'Hold',
  cancelStop: 'Annul',
  addStop: 'Extra',
  broadcast: 'Bulletin',
  eventLog: 'Train Sheet',
  drinkLog: 'Tab',
  scoreboard: 'Hall of Fame',
  awards: 'Golden Spikes',
  media: 'Freight',
  album: 'Roundhouse',
  simulationMode: 'Shakedown Run',
  simulationClock: 'Railroad Time',
  meetingPoint: 'Meet Point',
  straggler: 'Caboose',
  leftEarly: 'Deadhead',
  homeStation: 'Home Terminal'
} as const;

export type LabelKey = keyof typeof labels;

export function label(key: LabelKey): string {
  return labels[key];
}

// UI copy lives alongside the glossary so it can be changed in one place.
export const copy = {
  appTitle: 'Chug-a-Lug Choo-Choo',
  appSubtitle: 'Your next stop starts here.',
  loginTitle: 'Welcome aboard',
  loginIntro: 'Enter your name and the crew password from the family chat.',
  name: 'Your name',
  namePlaceholder: 'How the crew knows you',
  password: 'Crew password',
  login: 'Climb aboard',
  working: 'Please wait…',
  nameError: "Enter a name: 2 to 32 letters, numbers, spaces, or . ' -",
  passwordError: 'Enter the crew password.',
  genericError: 'Something went wrong. Please try again.',
  welcome: 'Welcome aboard,',
  role: 'You are part of the',
  comingSoon: 'Coming soon',
  homeIntro: 'You’re ready for the ride. Planning, live updates, and the album will arrive next.',
  notYou: 'Not you? Log out and enter your own name.',
  logout: 'Log out',
  footer: 'Family, friends, and the next train.',
  plannerTeaser: 'Propose stops, cheer the good ones, lock the winner.',
  plannerIntro: 'Anyone can start a draft and add stops. The Conductor runs the vote and locks The Route.',
  drafts: 'Drafts',
  pastRoutes: 'Locked and archived',
  newDraft: 'Start a draft',
  draftTitle: 'Draft title',
  draftTitlePlaceholder: 'e.g. West line classics',
  create: 'Create',
  noDrafts: 'No drafts yet. Start the first one.',
  status_draft: 'Draft',
  status_locked: 'Locked',
  status_archived: 'Archived',
  eventDate: 'Event day',
  startTime: 'At the first stop by',
  stops: 'Stops',
  addStop: 'Add a stop',
  noStops: 'No stops yet. Add the first bar.',
  arrive: 'Arrive',
  leave: 'Leave',
  layoverMinutes: 'min layover',
  layover: 'Layover',
  departure: 'Departure',
  moveUp: 'Move up',
  moveDown: 'Move down',
  layoverLower: 'layover',
  train: 'train',
  current: 'current',
  addAt: 'Add a stop at',
  noStopsTap: 'No stops yet. Tap a station circle to add the first bar.',
  walkMinutes: 'min walk',
  remove: 'Remove',
  removeConfirm: 'Remove this stop?',
  computing: 'Working out the trains…',
  noTrain: 'No train works here. Shorten a layover, change the start time, or move this stop.',
  noTrainsShort: 'no trains',
  noServiceLeg: 'has no trains on a',
  noServiceHint: 'Move this stop to a station that has trains that day.',
  sameStation: 'Same station, walk over.',
  walk: 'Walk',
  minutes: 'min',
  departs: 'departs',
  arrives: 'arrives',
  changeAt: 'change at',
  deleteDraft: 'Delete draft',
  deleteDraftConfirm: 'Delete this draft and all its stops?',
  notAffiliated: 'Schedule from Metra’s public feed. Not affiliated with Metra. Saturday timetable, published',
  pickStation: 'Pick a station',
  pickStationHint: 'Tap a station on the line or use the list. Aurora is at the top, Union Station at the bottom.',
  stationList: 'All stations',
  nearby: 'Best rated bars and restaurants within 250 m of',
  loadingNearby: 'Looking around the station…',
  noNearby: 'Nothing listed within 250 m of the station. Search by name instead.',
  searchByName: 'Search by name',
  searchPlaceholder: 'Bar or restaurant name',
  search: 'Search',
  searching: 'Searching…',
  noSearchResults: 'Nothing found. Add it by name only.',
  manualAdd: 'Add by name only',
  manualName: 'Name',
  add: 'Add',
  adding: 'Adding…',
  osmAttribution: 'Venue data © OpenStreetMap contributors',
  googleAttribution: 'Details and photos via Google',
  changeStation: 'Change station',
  kind_bar: 'Bar',
  kind_restaurant: 'Restaurant',
  kind_other: 'Place',
  openInMaps: 'Open in Google Maps',
  hours: 'Hours',
  hoursUnknown: 'Hours unknown. Call to confirm.',
  phone: 'Phone',
  website: 'Website',
  notes: 'Notes',
  notesPlaceholder: 'Deals, tips, who suggested it…',
  confirmedOpen: 'Confirmed open on event day',
  confirmPhone: 'Number called',
  photosPending: 'Fetching photos…',
  photosFailed: 'Photos unavailable.',
  retryPhotos: 'Try again',
  noPhotos: 'No photos yet.',
  save: 'Save',
  saved: 'Saved.',
  comments: 'Comments',
  commentPlaceholder: 'Say something…',
  post: 'Post',
  noComments: 'No comments yet.',
  delete: 'Delete',
  approvalIntro: 'The Conductor opens the vote. When the crew says go, the Conductor locks the route.',
  openVote: 'Open the vote',
  closeVote: 'Close the vote',
  voteOpen: 'The vote is open.',
  voteClosed: 'The vote is not open.',
  go: 'Go',
  nogo: 'No go',
  tally: 'Tally',
  lockRoute: 'Lock as The Route',
  lockConfirm: 'Lock this draft as The Route? Any other locked route is archived.',
  noRoute: 'No route is locked yet.',
  lockedOn: 'Locked on',
  backToPlanner: 'Back to the Route Planner',
  backToDraft: 'Back to the draft',
  editDraft: 'Edit the stops',
  doneEditing: 'Done editing',
  loadError: 'Could not load this. Check your connection and try again.',
  // Live day
  live: 'Live',
  noActiveRoute: 'No route is locked for today yet.',
  backToLive: 'Back to Live',
  stillToCome: 'Still to come',
  departLabel: 'Depart',
  arriveLabel: 'Arrive',
  run: 'Run',
  metraBnsf: 'Metra BNSF',
  leaveIn: 'Leave in',
  leaveNowSub: 'Leave now',
  walkFrom: 'min walk from',
  missedTrain: 'That train has gone. Counting down to the next one.',
  noTrainLeft: 'No train left today. Ask the Conductor.',
  timetableOnly: 'Timetable only — no live times since',
  timetableOnlyNoTime: 'Timetable only — no live times yet.',
  setOurStop: 'Not here? Set our stop',
  setOurStopTitle: 'Where is the crawl?',
  // The live editor
  blockNoPosition: 'Set where the crew is before saving.',
  blockAnchorMissing: 'The crew is at a stop you removed. Move the crew first, or put the stop back.',
  blockNoTrain: 'No train from',
  blockTo: 'to',
  blockHint: 'Shorten a layover, annul a stop, or move the crew.',
  bulletinPosition: 'We are still at',
  bulletinHold: 'Holding at',
  bulletinUntil: 'until the',
  bulletinHoldPlain: 'Staying longer at',
  bulletinAnnul: 'is annulled.',
  bulletinExtra: 'Extra stop:',
  bulletinReroute: 'Rerouted:',
  bulletinBefore: 'before',
  // Menu and notifications
  menu: 'Menu',
  close: 'Close the menu',
  notifications: 'Notifications',
  serviceAlerts: 'Service alerts',
  bulletins: 'Bulletins',
  noNotifications: 'Nothing to report.',
  bulletinsLater: 'Bulletins from the Conductor will appear here.',
  drinkScoreboard: 'Drink scoreboard',
  comingInM3: 'M3',
  theRoute: 'The Route',
  moreAlerts: 'more alerts',
  oneMoreAlert: 'more alert',
  stationOTC: 'Ogilvie',
  stationCUS: 'Union Station',
  inbound: 'Aurora → Chicago',
  outbound: 'Chicago → Aurora',
  offLine: 'Off the BNSF line',
  direction: 'Direction',
  routeMovedOn: 'The Route changed while you were editing. Reload and make the change again.',
  savedButBroken: 'Saved, but a leg after here has no train. Fix it and save again.',
  crewIsHere: 'The crew is here',
  crewIsHereSet: 'Move the crew here',
} as const;
