// Developer term -> UI label. The README glossary is the source of truth; keep them in sync.
export const labels = {
  planningPhase: 'Route Planner',
  itineraryDraft: 'Draft',
  lockedItinerary: 'The Route',
  approvalVote: 'Highball',
  like: 'Cheers',
  dislike: 'Pass',
  livePhase: 'Live',
  wrapUpPhase: 'Closing Time',
  admin: 'Conductor',
  users: 'Crew',
  userRoster: 'Crew Board',
  stop: 'Stop',
  dwell: 'Layover',
  trainLeg: 'Run',
  walk: 'Walk',
  venueCard: 'Stop card',
  departureBanner: 'Departure Board',
  firstWarning: 'Last Call',
  leaveNow: 'All Aboard',
  locationSharing: 'Position Report',
  checkIn: 'Punch',
  reroute: 'Reroute',
  hold: 'Hold',
  cancelStop: 'Annul',
  addStop: 'Extra',
  broadcast: 'Bulletin',
  eventLog: 'Train Sheet',
  drinkLog: 'Tab',
  scoreboard: 'Hall of Fame',
  awards: 'Golden Spikes',
  media: 'Freight',
  album: 'Roundhouse',
  simulationMode: 'Shakedown Run',
  simulationClock: 'Railroad Time',
  meetingPoint: 'Meet Point',
  straggler: 'Caboose',
  leftEarly: 'Deadhead',
  homeStation: 'Home Terminal'
} as const;

export type LabelKey = keyof typeof labels;

export function label(key: LabelKey): string {
  return labels[key];
}

// UI copy lives alongside the glossary so it can be changed in one place.
export const copy = {
  rehearsalTitle: 'Rehearsal — practice only',
  mainNav: 'Main',
  liveHint: 'Departure Board, Tab and crew chat',

  simRecorded: 'Recorded feed',
  simTimetable: 'Timetable rehearsal',
  simEnded: 'Ended',
  simPaused: 'Paused',
  simRunning: 'Running',
  simSynced: 'Synchronized',
  simUnsynced: 'Not synchronized — reconnect before making changes.',
  simPause: 'Pause',
  simResume: 'Resume',
  simSpeed: 'Playback speed',
  simForwardTime: 'Forward time (Chicago)',
  simSeek: 'Advance clock',
  simWindow: 'Playback window',
  simDisabled: 'Shakedown Run is not enabled here.',
  simFeedUnavailable: 'Rehearsal train data is unavailable. Check the recording and pinned timetable.',
  metraUnavailable: 'Metra schedule is not available yet. Try again in a minute.',
  simUnavailable: 'Railroad Time is unavailable. Check the rehearsal setup and try again.',
  simInvalidControl: 'Choose a supported speed or a valid forward time while paused.',
  simClockConflict: 'Railroad Time changed. Check the current clock and try again.',
  simClockBusy: 'The Route is being saved or recomputed. Try the clock control again shortly.',
  simAdminOnly: 'Only the Conductor can change Railroad Time.',

  appTitle: 'Chug-a-Lug Choo-Choo',
  appSubtitle: 'Your next stop starts here.',
  loginTitle: 'Welcome aboard',
  loginIntro: 'Enter your name and the crew password from the family chat.',
  name: 'Your name',
  namePlaceholder: 'How the crew knows you',
  password: 'Crew password',
  login: 'Climb aboard',
  working: 'Please wait…',
  nameError: "Enter a name: 2 to 32 letters, numbers, spaces, or . ' -",
  passwordError: 'Enter the crew password.',
  genericError: 'Something went wrong. Please try again.',
  welcome: 'Welcome aboard,',
  role: 'You are part of the',
  comingSoon: 'Coming soon',
  homeIntro: 'You’re ready for the ride. Planning, live updates, and the album will arrive next.',
  notYou: 'Not you? Log out and enter your own name.',
  logout: 'Log out',
  plannerTeaser: 'Propose stops, cheer the good ones, lock the winner.',
  plannerIntro: 'Anyone can start a draft and add stops. The Conductor runs the vote and locks The Route.',
  drafts: 'Drafts',
  pastRoutes: 'Locked and archived',
  newDraft: 'Start a draft',
  draftTitle: 'Draft title',
  draftTitlePlaceholder: 'e.g. West line classics',
  create: 'Create',
  noDrafts: 'No drafts yet. Start the first one.',
  status_draft: 'Draft',
  status_locked: 'Locked',
  status_archived: 'Archived',
  eventDate: 'Event day',
  startTime: 'At the first stop by',
  stops: 'Stops',
  addStop: 'Add a stop',
  noStops: 'No stops yet. Add the first bar.',
  arrive: 'Arrive',
  leave: 'Leave',
  layoverMinutes: 'min layover',
  layover: 'Layover',
  departure: 'Departure',
  moveUp: 'Move up',
  moveDown: 'Move down',
  layoverLower: 'layover',
  train: 'train',
  current: 'current',
  addAt: 'Add a stop at',
  noStopsTap: 'No stops yet. Tap a station circle to add the first bar.',
  walkMinutes: 'min walk',
  remove: 'Remove',
  removeConfirm: 'Remove this stop?',
  computing: 'Working out the trains…',
  noTrain: 'No train works here. Shorten a layover, change the start time, or move this stop.',
  noTrainsShort: 'no trains',
  noServiceLeg: 'has no trains on a',
  noServiceHint: 'Move this stop to a station that has trains that day.',
  sameStation: 'Same station, walk over.',
  walk: 'Walk',
  minutes: 'min',
  departs: 'departs',
  arrives: 'arrives',
  changeAt: 'change at',
  deleteDraft: 'Delete draft',
  deleteDraftConfirm: 'Delete this draft and all its stops?',
  notAffiliated: 'Schedule from Metra’s public feed. Not affiliated with Metra. Saturday timetable, published',
  pickStation: 'Pick a station',
  pickStationHint: 'Tap a station on the line or use the list. Aurora is at the top, Union Station at the bottom.',
  stationList: 'All stations',
  nearby: 'Best rated bars and restaurants within 250 m of',
  loadingNearby: 'Looking around the station…',
  noNearby: 'Nothing listed within 250 m of the station. Search by name instead.',
  searchByName: 'Search by name',
  searchPlaceholder: 'Bar or restaurant name',
  search: 'Search',
  searching: 'Searching…',
  noSearchResults: 'Nothing found. Add it by name only.',
  manualAdd: 'Add by name only',
  manualName: 'Name',
  add: 'Add',
  adding: 'Adding…',
  osmAttribution: 'Venue data © OpenStreetMap contributors',
  googleAttribution: 'Details and photos via Google',
  changeStation: 'Change station',
  kind_bar: 'Bar',
  kind_restaurant: 'Restaurant',
  kind_other: 'Place',
  openInMaps: 'Open in Google Maps',
  hours: 'Hours',
  hoursUnknown: 'Hours unknown. Call to confirm.',
  phone: 'Phone',
  website: 'Website',
  notes: 'Notes',
  notesPlaceholder: 'Deals, tips, who suggested it…',
  confirmedOpen: 'Confirmed open on event day',
  confirmPhone: 'Number called',
  photosPending: 'Fetching photos…',
  photosFailed: 'Photos unavailable.',
  retryPhotos: 'Try again',
  noPhotos: 'No photos yet.',
  save: 'Save',
  saved: 'Saved.',
  comments: 'Comments',
  commentPlaceholder: 'Say something…',
  post: 'Post',
  noComments: 'No comments yet.',
  delete: 'Delete',
  approvalIntro: 'The Conductor opens the vote. When the crew says go, the Conductor locks the route.',
  openVote: 'Open the vote',
  closeVote: 'Close the vote',
  voteOpen: 'The vote is open.',
  voteClosed: 'The vote is not open.',
  go: 'Go',
  nogo: 'No go',
  tally: 'Tally',
  lockRoute: 'Lock as The Route',
  lockConfirm: 'Lock this draft as The Route? Any other locked route is archived.',
  noRoute: 'No route is locked yet.',
  lockedOn: 'Locked on',
  backToPlanner: 'Back to the Route Planner',
  backToDraft: 'Back to the draft',
  editDraft: 'Edit the stops',
  doneEditing: 'Done editing',
  loadError: 'Could not load this. Check your connection and try again.',
  // Live day
  live: 'Live',
  noActiveRoute: 'No route is locked yet.',
  backToLive: 'Back to Live',
  practiceBadge: 'Practice',
  practiceHint: 'Timetable for the route’s date, at today’s time',
  makeCurrent: 'Make current',
  currentRoute: 'Current route',
  routeProgress: 'Route progress',
  tabTitle: 'Tab',
  drink_beer: 'Beer',
  drink_cocktail: 'Cocktail',
  drink_shot: 'Shot',
  drink_water: 'Non-alcoholic',
  drink_food: 'Food',
  undoDrink: 'Undo',
  tabYou: 'you',
  tabAdded: '+1',
  undoLast: 'Undo my last one here',
  tabClosed: 'The Tab opens when the crawl does.',
  postedAt: 'Posted',
  effectiveAt: 'Effective',
  notificationTimeUnknown: 'Time not supplied',
  venueReviews: 'Reviews from Google',
  currentStop: 'Current stop',
  addPhoto: 'Photo',
  bulletinAction: 'Bulletin',
  conductorBulletinOnly: 'Only the Conductor can send Bulletins',
  crewChat: 'Crew chat',
  chatCrew: 'Crew',
  chatAdded: 'Added',
  chatDrink: 'a drink',
  chatEmpty: 'The crew’s messages, Bulletins and Tab activity will appear here.',
  chatLoadError: 'Chat could not refresh. Reconnecting…',
  messagePlaceholder: 'Message the crew…',
  sendMessage: 'Send',
  deleteMessage: 'Delete',
  showEarlier: 'Show earlier',
  chatPhoto: 'shared a photo',
  milestoneAuthor: 'Milestone',
  milestoneFirst: 'First of the day:',
  milestoneTotalBefore: 'The crew just hit',
  milestoneTotalAfter: 'drinks!',
  milestoneLead: 'took the lead',
  milestonePhoto: 'First photo at',
  takePhoto: 'Take a photo',
  addFreight: 'Add a photo',
  uploading: 'Sending…',
  uploadTooBig: 'That file is over 90 MB — the tunnel will not take it.',
  uploadFailed: 'An upload failed. Try the unsent files again.',
  uploadUnsupportedType: 'Only photos and videos can be sent.',
  uploadSent: 'sent.',
  uploadNotSent: 'not sent.',
  noFreightYet: 'No photos from this stop yet.',
  openFreightPhoto: 'Open photo',
  openFreightVideo: 'Open video',
  noSignal: 'No signal — try again in a minute.',
  showingMirror: 'Showing the last known plan, saved',
  minutesAgo: 'min ago',
  departLabel: 'Depart',
  arriveLabel: 'Arrive',
  run: 'Run',
  metraBnsf: 'Metra BNSF',
  leaveIn: 'Leave in',
  leaveNowSub: 'Leave now',
  walkFrom: 'min walk from',
  missedTrain: 'That train has gone. Counting down to the next one.',
  missedTrainShort: 'Train gone',
  noTrainLeft: 'No train left today. Ask the Conductor.',
  timetableOnly: 'Timetable only — no live times since',
  timetableOnlyNoTime: 'Timetable only — no live times yet.',
  // The live editor
  liveRouteWarning: 'This is The Route and the crew is riding it. Nothing changes for them until you save.',
  savePlan: 'Save and tell the crew',
  saving: 'Saving…',
  saveFailed: 'Saved partly — check The Route and try again.',
  checkingRoute: 'Checking the route…',
  checkFailed: 'Could not check the route. You can still try Save.',
  blockNoPosition: 'Set where the crew is before saving.',
  blockAnchorMissing: 'The crew is at a stop you removed. Move the crew first, or put the stop back.',
  blockNoTrain: 'No train from',
  blockTo: 'to',
  blockHint: 'Shorten a layover, annul a stop, or move the crew.',
  bulletinPosition: 'We are still at',
  bulletinHold: 'Holding at',
  bulletinUntil: 'until the',
  bulletinHoldPlain: 'Staying longer at',
  bulletinAnnul: 'is annulled.',
  bulletinExtra: 'Extra stop:',
  bulletinReroute: 'Rerouted:',
  bulletinBefore: 'before',
  tellTheCrew: 'Tell the crew?',
  bulletinHint: 'This is pinned on everyone’s screen until they tap Got it.',
  sendBulletin: 'Send it',
  skipBulletin: 'Save without telling them',
  gotIt: 'Got it',
  fromTheConductor: 'From the Conductor',
  postBulletin: 'Post a Bulletin',
  seenBulletin: 'Seen',
  unseenBulletin: 'Not seen',
  // Menu and notifications
  menu: 'Menu',
  close: 'Close the menu',
  notifications: 'Notifications',
  serviceAlerts: 'Service alerts',
  bulletins: 'Bulletins',
  noNotifications: 'Nothing to report.',
  bulletinsLater: 'Bulletins from the Conductor will appear here.',
  drinkScoreboard: 'Drink scoreboard',
  comingInM5: 'M5',
  theRoute: 'The Route',
  moreAlerts: 'more alerts',
  oneMoreAlert: 'more alert',
  stationOTC: 'Ogilvie',
  stationCUS: 'Union Station',
  inbound: 'Aurora → Chicago',
  outbound: 'Chicago → Aurora',
  offLine: 'Off the BNSF line',
  direction: 'Direction',
  routeMovedOn: 'The Route changed while you were editing. Reload and make the change again.',
  savedButBroken: 'Saved, but a leg after here has no train. Fix it and save again.',
  crewIsHere: 'The crew is here',
  crewIsHereSet: 'Move the crew here',
  photoViewer: 'Photo viewer',
  closeViewer: 'Close',
  downloadOriginal: 'Download original',
  stopDetails: 'Stop details',
  walkThere: 'Walk there',
  callStop: 'Call',
  editDetails: 'Edit details',
  confirmedOpenBadge: 'Confirmed open on event day',
  otherDays: 'Other days',
  previousStop: 'Previous stop',
  nextStop: 'Next stop',
  closeSheet: 'Close',
  googlePhoto: 'Photo via Google',
  leaderboard: 'Leaderboard',
  you: 'you',
} as const;

// Operator-facing rehearsal setup messages; these never include passwords or tokens.
export const simSetup = {
  invalid: (field: string) => `Invalid rehearsal configuration: ${field}.`,
  runMismatch: 'This run has different saved settings. Use its original settings or choose a new run name.',
  unsafePath: 'Rehearsal storage must be a real directory inside this checkout, without symlinks.',
  occupiedPort: 'A rehearsal port is already in use. Stop its owner or choose different rehearsal ports.',
  locked: 'Another setup operation owns this run. If it crashed, inspect the run before removing its operation lock.',
  interruptedSeed: 'This run has an incomplete seed. Its data was preserved; inspect it and use a new run name to start fresh.',
  partialStack: 'Only part of this rehearsal is running. Stop this run before starting it again.',
  missingRun: 'This rehearsal does not exist.',
  invalidCredentials: 'The run credentials are missing or invalid. No credentials will be inherited from production.',
  notEmpty: 'The rehearsal database already contains records. Refusing to overwrite it.',
  clockMismatch: 'The persisted clock does not belong to this rehearsal.',
  requestFailed: (status: number) => `Rehearsal request failed (HTTP ${status}).`,
  commandFailed: 'The rehearsal Docker command failed. Run data has been preserved.',
  timeout: 'The rehearsal did not become ready in time. Run data has been preserved.',
  invalidLegs: 'The planner did not persist a complete, feasible fixture route.',
  seedStop: (name: string) => `Rehearsal ${name}`,
  usage: 'Usage: node web/scripts/sim.mjs start RUN SOURCE | status RUN | stop RUN. SOURCE: fixture, fixture-recording, or an ID under data/recordings.',
  ready: 'Rehearsal ready. The live clock and UI integration are still pending.',
  credentials: 'Test passwords are in the private credentials.env file under this run directory.',
  identities: 'Test identities: Rehearsal Conductor and Rehearsal Crew.',
  stopped: 'Rehearsal stopped. Its data is preserved.',
  lanNote: 'LAN HTTP supports functional checks; phone PWA/offline checks require dedicated HTTPS origins.',
} as const;

export const recordingCopy = {
  invalid: 'Invalid or incompatible recording metadata, schedule, or snapshot reference.',
  exists: 'This recording already has metadata. Refusing to replace its archive or history.',
  recordUsage: 'Usage: just record NAME DATE WINDOW_START_UTC WINDOW_END_UTC',
  indexUsage: 'Usage: just index-recording NAME MATCHING_ZIP DATE WINDOW_START_UTC WINDOW_END_UTC',
  noToken: 'METRA_API_TOKEN is not set; nothing to record.',
  outsideWindow: 'The recording window must include the current time.',
  started: 'Recording with an archived timetable. Ctrl-C stops after the current poll.',
  stopped: 'Recording stopped. Snapshots and poll history are preserved.',
  failed: 'Recording stopped after a storage or setup failure. Inspect the recording directory.',
  indexed: 'Legacy recording indexed. Freshness is conservative because poll history is unavailable.',
  generated: 'Deterministic rehearsal recording generated.',
} as const;

/** Route strip marks by venue kind; an `other` stop gets a plain dot. */
export const venueIcons: Record<string, string> = { bar: '🍺', restaurant: '🍽️' };
export const drinkIcons: Record<string, string> = { shot: '🥃', cocktail: '🍸', beer: '🍺', water: '🧃', food: '🍽️' };
