import { expect, test, devices, type Page } from '@playwright/test';
import { login } from '../e2e/helpers';
import { admin } from './setup';
import { copy } from '../../src/lib/labels';
async function token(page: Page) {
  const cookie = (await page.context().cookies()).find(c => c.name === 'pb_auth_rehearsal');
  return JSON.parse(decodeURIComponent(cookie!.value)).token;
}
async function clock(page: Page) {
  const res = await page.request.get('/api/sim/clock', { headers: { Authorization: await token(page) } });
  expect(res.ok()).toBe(true); return res.json();
}
async function change(page: Page, body: object) {
  const current = await clock(page);
  const res = await page.request.post('/api/sim/clock', { headers: { Authorization: await token(page) }, data: { expectedRevision: current.revision, ...body } });
  expect(res.ok(), await res.text()).toBe(true); return res.json();
}

test('three sessions rehearse clock, replay, route edits, Tab, Freight and reconnect', async ({ page, browser }, info) => {
  test.setTimeout(120_000);
  await page.goto('/login');
  await expect(page.getByTestId('rehearsal-badge')).toContainText('Rehearsal');
  await login(page, 'Rehearsal Conductor', process.env.ADMIN_PASSWORD!);
  await expect(page.getByTestId('nav-live').or(page.getByTestId('tab-bar')).first()).toBeVisible();
  const crewContext = await browser.newContext({ ...devices['iPhone 13'], baseURL: 'http://127.0.0.1:15173' });
  const otherContext = await browser.newContext({ ...devices['iPhone 13'], baseURL: 'http://127.0.0.1:15173' });
  const externalRequests: string[] = [];
  await crewContext.route(/^https?:\/\/(?!127\.0\.0\.1[:/])/, route => { externalRequests.push(route.request().url()); return route.abort(); });
  const crew = await crewContext.newPage(), other = await otherContext.newPage();
  try {
    await crew.clock.setFixedTime(new Date(Date.now() - 3 * 60 * 60 * 1000));
    await login(crew, 'Rehearsal Crew One', process.env.CREW_PASSWORD!);
    await login(other, 'Rehearsal Crew Two', process.env.CREW_PASSWORD!);
    await page.goto('/sim'); await crew.goto('/live'); await other.goto('/live');
    const indicator = page.getByTestId('simulation-status');
    await expect(indicator).toHaveAttribute('data-status', /Paused/);
    await expect(page.getByTestId('rehearsal-badge')).toContainText(`${copy.rehearsalTitle} — `);
    await expect(crew.getByTestId('simulation-status')).toHaveAttribute('data-status', await indicator.getAttribute('data-status') ?? '');
    await expect(other.getByTestId('simulation-status')).toHaveAttribute('data-status', await indicator.getAttribute('data-status') ?? '');
    const initialHeaders = { Authorization: await token(page) };
    const normal = await (await page.request.get('/api/metra/next?from=CUS&to=LAGRANGE&date=2026-12-26', { headers: initialHeaders })).json();
    expect(normal.trips.find((t: { tripId: string }) => t.tripId === 'BN1')?.delayMin).toBe(0);
    const initialAlerts = await (await page.request.get('/api/metra/alerts', { headers: initialHeaders })).json();
    expect(initialAlerts.alerts.some((a: { header: string }) => a.header === 'Fixture delay')).toBe(true);
    await crew.goto('/sim'); await expect(crew.getByTestId('sim-toggle')).toHaveCount(0);
    expect((await crew.request.post('/api/sim/clock', { headers: { Authorization: await token(crew) }, data: { expectedRevision: 1, action: 'resume' } })).status()).toBe(403);
    await page.getByRole('button', { name: '10×', exact: true }).click();
    await expect(page.getByRole('button', { name: '10×', exact: true })).toHaveAttribute('aria-pressed', 'true');
    const before = await clock(page);
    await page.getByTestId('sim-toggle').click();
    await expect(indicator).toHaveAttribute('data-status', /Running/);
    await expect(other.getByTestId('simulation-status')).toHaveAttribute('data-status', /Running/, { timeout: 7000 });
    await page.getByTestId('sim-toggle').click();
    await expect(indicator).toHaveAttribute('data-status', /Paused/);
    const paused = await clock(page);
    expect(Date.parse(paused.eventNow) - Date.parse(before.eventNow)).toBeGreaterThan(0);
    expect(Date.parse(paused.eventNow) - Date.parse(before.eventNow)).toBeLessThan(90_000);
    const stale = await page.request.post('/api/sim/clock', { headers: { Authorization: await token(page) }, data: { expectedRevision: before.revision, action: 'resume' } });
    expect(stale.status()).toBe(409); expect((await stale.json()).clock.revision).toBe(paused.revision);
    const backwards = await page.request.post('/api/sim/clock', { headers: { Authorization: await token(page) }, data: { expectedRevision: paused.revision, action: 'seek', at: before.windowStart } });
    expect(backwards.status()).toBe(400);
    await page.getByLabel('Forward time (Chicago)').fill('12:25');
    await page.getByRole('button', { name: 'Advance clock' }).click();
    await expect(other.getByTestId('simulation-status')).toContainText('12:25', { timeout: 7000 });
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    await expect(indicator).toBeInViewport();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: info.outputPath('controls.png'), fullPage: true });
    const headers = { Authorization: await token(page) };
    const next = await (await page.request.get('/api/metra/next?from=CUS&to=LAGRANGE&date=2026-12-26', { headers })).json();
    expect(next.source).toBe('recording');
    expect(next.trips.find((t: { tripId: string }) => t.tripId === 'BN1')?.delayMin).toBe(5);
    expect(next.trips.some((t: { tripId: string }) => t.tripId === 'BN3')).toBe(false);
    const feeds = await (await page.request.get('/api/metra/status', { headers })).json();
    expect(feeds.feeds.positions.mode).toBe('stale'); expect(feeds.feeds.tripupdates.mode).toBe('live');
    const expiredAlerts = await (await page.request.get('/api/metra/alerts', { headers })).json();
    expect(expiredAlerts.alerts).toEqual([]);
    // Delay one actual clock response; a later response must win even after this one arrives.
    let release!: () => void, captured!: () => void;
    const hold = new Promise<void>(resolve => { release = resolve; });
    const seen = new Promise<void>(resolve => { captured = resolve; });
    let firstClock = true;
    await crew.route('**/api/sim/clock', async route => {
      if (!firstClock) return route.continue();
      firstClock = false;
      const response = await route.fetch(); captured(); await hold;
      await route.fulfill({ response });
    });
    await crew.evaluate(() => window.dispatchEvent(new Event('focus'))); await seen;
    await change(page, { action: 'rate', rate: 30 });
    await expect(crew.getByTestId('simulation-status')).toHaveAttribute('data-status', /30×/, { timeout: 7000 });
    release();
    await expect(crew.getByTestId('simulation-status')).toHaveAttribute('data-status', /30×/);
    await crew.unrouteAll({ behavior: 'wait' });
    const pb = await admin();
    const route = (await pb.collection('itineraries').getFullList())[0];
    await page.goto(`/plan/${route.id}/edit`);
    await page.getByTestId('set-here-0').click();
    await page.getByTestId('dwell-0').selectOption('30');
    await expect(page.getByTestId('save-plan')).toBeEnabled();
    const preview = page.waitForResponse(r => r.url().includes('/api/plan/preview') && r.request().method() === 'POST');
    await change(page, { action: 'rate', rate: 5 });
    expect((await (await preview).json()).clockRevision).toBe((await clock(page)).revision);
    await expect(page.getByTestId('save-plan')).toBeEnabled();
    page.on('dialog', dialog => dialog.accept());
    await page.getByTestId('remove-1').click();
    // The real staged venue picker, using its manual option and isolated disabled Places source.
    await page.getByRole('button', { name: 'Add a stop at La Grange Road' }).click();
    await page.getByTestId('manual-name').fill('Rehearsal Added Venue');
    await page.getByTestId('manual-add').click();
    await expect(page.getByText('Rehearsal Added Venue', { exact: true })).toBeVisible();
    const submissions: { id: string; body: string }[] = [];
    await page.route('**/api/plan/commit', async request => {
      submissions.push(request.request().postDataJSON().bulletin);
      const response = await request.fetch();
      expect(response.ok(), await response.text()).toBe(true);
      if (submissions.length === 1) await request.abort('failed');
      else await request.fulfill({ response });
    });
    await page.getByTestId('save-plan').click();
    await page.getByTestId('bulletin-body').fill('Rehearsal: continue to La Grange.');
    await page.screenshot({ path: info.outputPath('bulletin.png'), fullPage: false });
    await page.getByTestId('bulletin-send').click();
    await expect(page.locator('.savebar').getByRole('alert')).toBeVisible();
    await expect(page.getByTestId('bulletin-body')).toHaveValue('Rehearsal: continue to La Grange.');
    await expect(page.getByTestId('preview-status')).toHaveCount(0);
    await page.getByTestId('bulletin-send').click();
    await expect(page).toHaveURL(new RegExp(`/plan/${route.id}$`));
    expect(submissions).toHaveLength(2); expect(submissions[1]).toEqual(submissions[0]);
    expect(await pb.collection('broadcasts').getFullList()).toHaveLength(1);
    await other.getByTestId('bulletin-ack').click();
    await expect(other.getByTestId('pinned-bulletin')).toBeHidden();
    await crew.goto('/live');
    await expect(crew.getByTestId('departure-board')).toBeVisible();
    await crew.getByTestId('drink-beer').click();
    await expect(crew.getByTestId('tab-undo')).toBeVisible();
    await crew.getByTestId('drink-water').click();
    await expect(crew.getByTestId('drink-water').locator('.count')).toHaveText('1');
    await crew.getByTestId('tab-undo').click();
    await expect(crew.getByTestId('drink-water').locator('.count')).toHaveText('0');
    const drinks = await pb.collection('drink_entries').getFullList();
    expect(drinks).toHaveLength(1); expect(drinks[0].kind).toBe('beer');
    expect(new Date(drinks[0].at).toISOString()).toBe('2026-12-26T18:25:00.000Z');
    await crew.getByTestId('freight-input').setInputFiles({ name: 'rehearsal.gif', mimeType: 'image/gif', buffer: Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7', 'base64') });
    await expect(crew.getByTestId('freight-strip').locator('img')).toHaveCount(1);
    expect(externalRequests).toEqual([]);
    const media = await pb.collection('media').getFullList();
    expect(Math.abs(new Date(media[0].taken_at).getTime() - Date.now())).toBeLessThan(60_000);
    const bulletins = await pb.collection('broadcasts').getFullList();
    expect(new Date(bulletins[0].at).toISOString()).toBe(new Date(drinks[0].at).toISOString());
    const anchors = await pb.collection('checkins').getFullList({ sort: '-at,-action_order' });
    expect(new Date(anchors[0].at).toISOString()).toBe('2026-12-26T18:25:00.000Z');
    expect((await pb.collection('legs').getFullList()).length).toBe(2);
    const savedStops = await pb.collection('stops').getFullList();
    expect(savedStops.some(s => s.name === 'Rehearsal Added Venue')).toBe(true);
    expect(savedStops.find(s => s.name === 'Rehearsal Tap')?.dwell_min).toBe(30);
    const logs = await pb.collection('event_log').getFullList();
    expect(logs.some(row => new Date(row.at).toISOString() === '2026-12-26T18:25:00.000Z')).toBe(true);
    await other.goto('/crew');
    await expect(other.getByTestId('crew-row').filter({ hasText: 'Rehearsal Crew One' }).locator('.tab > span[title="Beer"]')).toContainText('1');
    await crew.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    await expect(crew.getByTestId('simulation-status')).toBeInViewport();
    await crew.evaluate(() => window.scrollTo(0, 0));
    await crew.screenshot({ path: info.outputPath('board.png'), fullPage: true });
    await crewContext.setOffline(true);
    await expect(crew.getByTestId('simulation-status')).toHaveAttribute('data-status', /Not synchronized/);
    await crew.getByTestId('drink-beer').click();
    await expect(crew.getByRole('alert')).toHaveText(copy.noSignal);
    expect((await pb.collection('drink_entries').getFullList()).length).toBe(1);
    await change(page, { action: 'seek', at: '2026-12-26T18:26:00.000Z' });
    await crewContext.setOffline(false);
    await expect(crew.getByTestId('simulation-status')).toContainText('12:26', { timeout: 7000 });
    await crew.getByTestId('drink-water').click();
    await expect(crew.getByTestId('drink-water').locator('.count')).toHaveText('1');
    // The count updates optimistically on tap; wait for the toast (shown only once the server has
    // confirmed the write) before reading the row back through a separate connection.
    await expect(crew.getByTestId('tab-toast')).toBeVisible();
    const after = await pb.collection('drink_entries').getFullList({ sort: '-action_order' });
    expect(new Date(after[0].at).toISOString()).toBe('2026-12-26T18:26:00.000Z');
    await change(page, { action: 'seek', at: '2026-12-27T00:10:00.000Z' });
    await expect(crew.getByTestId('simulation-status')).toHaveAttribute('data-status', /Ended/, { timeout: 7000 });
    const tail = await (await page.request.get('/api/metra/status', { headers })).json();
    expect(tail.feeds.tripupdates.mode).toBe('stale');
  } finally { await crewContext.close(); await otherContext.close(); }
});
